services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  frontend:
    image: node:lts-bookworm-slim
    ports:
      - "5173:5173"
    working_dir: /frontend
    command: npx vite --host
    volumes:
      - ./frontend:/frontend
  # backend:
  #   environment:
  #     DB_HOST: "db"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile-env
  #   volumes:
  #     - ./backend:/backend
