services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  frontend:
    image: node:lts-bookworm-slim
    ports:
      - "5173:5173"
    working_dir: /frontend
    command: npx vite --host
    volumes:
      - ./frontend:/frontend
  backend:
    image: node:lts-bookworm
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://test:test@db:5432/test?schema=public"
    depends_on:
      - db
    working_dir: /backend
    command: npm run dev
    # build:
      # context: ./backend
      # dockerfile: Dockerfile-env
    volumes:
      - ./backend:/backend
